# Generated by Django 4.2.3 on 2023-07-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
        migrations.AddField(
            model_name='variacao',
            name='preco',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
